repos:

# Automatic source code formatting
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    args: [--safe, --quiet]

# Syntax check and some basic flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-ast
  - id: flake8
    args: ['--max-line-length=88', '--select=E711,E714,E721,E722,E901,F401,F822,F901,W191,W602,W603,W604,W606']
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=200']
